# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170603_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
